FROM ruby:2.7

LABEL maintainer="test@example.com" \
      description="Ruby 2.7 with Sinatra"

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle install --without development test

COPY . .

EXPOSE 4567

CMD ["bundle", "exec", "ruby", "app.rb"]
