FROM php:7.4-apache

LABEL maintainer="test@example.com" \
      description="PHP 7.4 with Apache"

RUN docker-php-ext-install \
    pdo \
    pdo_mysql \
    mysqli \
    && a2enmod rewrite

WORKDIR /var/www/html

COPY . .

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80

CMD ["apache2-foreground"]
