FROM redis:5

LABEL maintainer="test@example.com" \
      description="Redis 5"

COPY redis.conf /usr/local/etc/redis/redis.conf

EXPOSE 6379

HEALTHCHECK --interval=5s --timeout=3s --start-period=5s --retries=3 \
    CMD redis-cli ping

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
