FROM jenkins/jenkins:2.164.1

LABEL maintainer="test@example.com" \
      description="Jenkins 2.164.1 from paper evaluation"

USER root

RUN apt-get update && apt-get install -y \
    git \
    curl \
    ssh \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER jenkins

ENV JAVA_OPTS="-Xmx512m -Xms512m"

COPY init.groovy.d/ /usr/share/jenkins/ref/init.groovy.d/
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

RUN while IFS= read -r plugin; do \
        echo "Installing plugin: $plugin"; \
        curl -sSL "https://updates.jenkins.io/latest/$plugin.hpi" -o "/usr/share/jenkins/plugins/$plugin.hpi"; \
    done < /usr/share/jenkins/ref/plugins.txt

EXPOSE 8080 50000

CMD ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
