FROM jenkins/jenkins:lts

LABEL maintainer="test@example.com" \
      description="Jenkins LTS"

USER root

RUN apt-get update && apt-get install -y \
    git \
    curl \
    ssh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER jenkins

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

EXPOSE 8080 50000

CMD ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
